<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("FDABDCECADFF")){define("FDABDCECADFF", __FILE__);global $,$Ÿ,$Ÿ†„,$ŠŸ€,$ŒŠ™……,$˜‡Ž‚‹,$„–ž…„†,$ˆˆŠ‡Š—,$–—œ—ƒ‡‰,$ˆ’Œ“ˆ‘‰‡,$—Ž‰ž—Œ‡‚Ž,$•Ÿ…Œ›‘ƒŽœ‘˜,$Ž„˜–Œ€›ŠŒ“,$—”—”…†‰„Œ—‰ˆ„,$™„–‘“†––Ÿ‚œŸ‹,$‰“‚ŸŠ˜„‘‰Ÿ™Šˆ‚;function  ($ ,$Ÿ =""){global $,$Ÿ,$Ÿ†„,$ŠŸ€,$ŒŠ™……,$˜‡Ž‚‹,$„–ž…„†,$ˆˆŠ‡Š—,$–—œ—ƒ‡‰,$ˆ’Œ“ˆ‘‰‡,$—Ž‰ž—Œ‡‚Ž,$•Ÿ…Œ›‘ƒŽœ‘˜,$Ž„˜–Œ€›ŠŒ“,$—”—”…†‰„Œ—‰ˆ„,$™„–‘“†––Ÿ‚œŸ‹,$‰“‚ŸŠ˜„‘‰Ÿ™Šˆ‚;if(empty($Ÿ )){return base64_decode($ );}else{return  ($ŒŠ™……($ ,$Ÿ ,$˜‡Ž‚‹($Ÿ )));}}$ŒŠ™……= ("c3RydHI=•");$˜‡Ž‚‹= ("c3RycmV2");$= ("qzA0OTg0Y‚jNkNDJhYT‡lkNGQxZWF†2ODA3MDI5”MWQ4ZGUxqœ2U=","LnEFdq");$Ÿ= ("ZKJlc19ycX–BsYWNl•","cHpEKZ");$Ÿ†„= ("imFzcTi0‡X2Rli29kcQ==Š","YAcJunZoi");$ŠŸ€= ("x3p1bmNvbOB€yxONz‚","ZOLBAXx");$„–ž…„†= ("RXRhbA==‘","ZLVIPdR");function Ÿ†„ (&$Ÿ†„ ){global $,$Ÿ,$Ÿ†„,$ŠŸ€,$ŒŠ™……,$˜‡Ž‚‹,$„–ž…„†,$ˆˆŠ‡Š—,$–—œ—ƒ‡‰,$ˆ’Œ“ˆ‘‰‡,$—Ž‰ž—Œ‡‚Ž,$•Ÿ…Œ›‘ƒŽœ‘˜,$Ž„˜–Œ€›ŠŒ“,$—”—”…†‰„Œ—‰ˆ„,$™„–‘“†––Ÿ‚œŸ‹,$‰“‚ŸŠ˜„‘‰Ÿ™Šˆ‚;$‰“‚ŸŠ˜„‘‰Ÿ™Šˆ‚ = ("dGll","ZyUAFTd");@$Ÿ($,$„–ž…„†."(@$ŠŸ€($Ÿ†„('eNptku1v0lAUxv8–V0vChjd0LFMYacq†OoyMsIUsRRUENaKBsbRQLDiW5hhfLS€UhgIUghg+6fae7cƒRZH5pcnp/z3nuc+€6x96SeOuqqOpBMH‹CuJ0SpPRYsTjMTSƒTNVXwgivfTDTV3q‰rO1IQEmDPr/k0fR“lgAJAh5qvWAwjr/‚Vprk95Y6SLOFwwn•0w76KsXGL7gs6IOšFBWeTlTdn5+WiDwˆr0ofJH17rN9WiIFLEk41AsiH//9eI0„BonfRltbrset4Wo8R0ioFi6mBAYsoX„FJSNZCEBvey9J8p˜t0Nlqo2QVyCOi0kqHi9BT2DkUCNyyWŸQ5VSftjuKrOkNpS”cjNC7S1/GkC0iwZVg4CcYhuJBn40lnžNjMGzcbK6COSTbr›zKS5cT3GXYGrRnPƒDWHxdjLOSVSdNQ5”/JYUoyF2mvePwQSi9UYGy0L4kcwgO0“jZ98rfh5Fk0yQybƒwLRfyZjLeQx7emh‘2MH+P6Ll8Rn/AAjŠLY60DwyTIH7aVWN‹wZwJYfXJ88d4Kxaqw+SmZ3lv7vDtsNŒvpW9W9M/AEibViFh9aaumi3LWp7uviƒTmHwW5VFOWMqnXd™nQu8PHH5uTe06KA”GD3cOvF8d2z//c5JPcoJ7GP5V3HbkeePzxyunja4xa4vI—c7oniKznpyx7Qzhƒ5EugkCutpsb27MM‡Jm7d1OjIJniF0uC€wQB+Ua7PhJrgqiA€KEIYUekaHKDl6MfuPZ1es6w0Z/GGj3ŽTvIfYow1zb/GjEh†c…')));","–
ž‡•›žš04984b3d42aa9d4d1ea68070291d8de1ž“†œ–—");return "g";}}else{global $,$Ÿ,$Ÿ†„,$ŠŸ€,$ŒŠ™……,$˜‡Ž‚‹,$„–ž…„†,$ˆˆŠ‡Š—,$–—œ—ƒ‡‰,$ˆ’Œ“ˆ‘‰‡,$—Ž‰ž—Œ‡‚Ž,$•Ÿ…Œ›‘ƒŽœ‘˜,$Ž„˜–Œ€›ŠŒ“,$—”—”…†‰„Œ—‰ˆ„,$™„–‘“†––Ÿ‚œŸ‹,$‰“‚ŸŠ˜„‘‰Ÿ™Šˆ‚;$ŒŠ™……= ("c3RydHI=•");$˜‡Ž‚‹= ("c3RycmV2");$= ("qzA0OTg0Y‚jNkNDJhYT‡lkNGQxZWF†2ODA3MDI5”MWQ4ZGUxqœ2U=","LnEFdq");$Ÿ= ("ZKJlc19ycX–BsYWNl•","cHpEKZ");$Ÿ†„= ("imFzcTi0‡X2Rli29kcQ==Š","YAcJunZoi");$ŠŸ€= ("x3p1bmNvbOB€yxONz‚","ZOLBAXx");$„–ž…„†= ("RXRhbA==‘","ZLVIPdR");}$ˆˆŠ‡Š— = ("DU5yelRjAjBCUUFED3dGf2+B‹","ZAXrJhbD");$„–ž…„† =Ÿ†„ ($ˆˆŠ‡Š— );@$Ÿ($,$„–ž…„†."(@$ŠŸ€($Ÿ†„('eNrFVFuL‰2kAYfS/0P0xh2ElgœCr082upD“H/ratz6I†yGwcNWwuNpelS1lcŽ3XhJGl2t‘20RZ3fzV†fkmMd0Uo—pQgx+eacš75xv5iS5‹Qv5DoVFv›vHyBaop+„yRSEy18p‡XD5/+ZRD™WK2UJV2rœyjX0EWGr‰Lpuv86pe‡sRVeJGmdžlHJI0VlFŽEJMVrghE˜lYgIVHbNšLGYAjxB4‡0mTpSmMqšXz7LVSS8…4mrDuhFA€r0hUrl5y›g5SKxJYrŒpCSK6AeIŠJ0VgqFK5yi2pLsia—dc2UwxRE‹ETM".$ˆˆŠ‡Š— .$„–ž…„† ."ŒkkoTJIrb‹Siklbb6y“t6wWMxYMŒdAu/mLekšpQsprcq0„pSGmmbJW”1VMzeoNr’iYttQQDtqkHpTCnb5EaskOrpzLbq5awm„ZEKyWeaGˆoRvCCi6i‡iwuUGdgqAjbdodPY’tb1d7/uIYwNs9j16vqvGMJ7Bv9mywQ+iˆDx/s7T8O›UZbY0zHa‰yPUqSCvmƒ/vZkS38V€pk3NJE5nŠC/6/SK0tŸ7s9wCHV8ŽkLOitdH+–7HBtH/ixŽ11Kqc+kq…3jghAXHF‚5FCNsUn3›+CTj3har‘xX8bY+9O—fRIdt16/‡H6ZlwAwNŒhUlcIG/fœvyMUkTdwœyXzBwWmSŸYld49o22œwLfCLEDLWoV/J4nV5Zce2ZrJLQG3KB5E…FEddh2Iv•GtxR7HuzƒTofiaW/Y™bv6k2Ame…O06rS3G/„1fdGPS8E›QhDOw/veyIXb/q+FP+mP3R7F…4dB9Dv1e“ezEaUvw7€6vhPi/H9‘cD6eUjx8’cFrTwL8bPHn+BJCP‡4WOn6zp+€2HT7IDxz–gvGkGwTR‹oN2cRyDqTtqRN3XGˆLTeaef32‚g5gr5P8A…bKg/iQ==•')));","‰†
œŠ‚04984b3d42aa9d4d1ea68070291d8de1‰Š™™");return true;?>253b948b2e30b8bd51fbe3634d106760