<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("AFCFFCBDFFFBA")){define("AFCFFCBDFFFBA", __FILE__);global $„,$•›,$”Ž,$ˆ†˜Ž,$ŽŽ—Ÿ,$ˆŸ“•“Œ,$ŽŒœœ•‚,$Ÿ™„…”‡›,$ƒ‚œ’‹‰,$‹†ˆŸœœŒŠˆ‰,$‡Ÿ‹‹Ÿœ„ƒ‚š‹,$žž€›“‡›ž“‚,$†“ŸƒŠŠ“Œ–Ÿ‹,$“ƒ—žœ•š—˜˜‹,$”‰”—‘‡–•ˆ‚“•Š,$•œŸ™Œ–˜‰Œ•„„Ž;function „ ($„ ,$•› =""){global $„,$•›,$”Ž,$ˆ†˜Ž,$ŽŽ—Ÿ,$ˆŸ“•“Œ,$ŽŒœœ•‚,$Ÿ™„…”‡›,$ƒ‚œ’‹‰,$‹†ˆŸœœŒŠˆ‰,$‡Ÿ‹‹Ÿœ„ƒ‚š‹,$žž€›“‡›ž“‚,$†“ŸƒŠŠ“Œ–Ÿ‹,$“ƒ—žœ•š—˜˜‹,$”‰”—‘‡–•ˆ‚“•Š,$•œŸ™Œ–˜‰Œ•„„Ž;if(empty($•› )){return base64_decode($„ );}else{return „ ($ˆŸ“•“Œ($„ ,$•› ,$„($•› )));}}$„=„ ("c3RycmV2‘");$ˆŸ“•“Œ=„ ("c3RydHI=˜");$ŽŽ—Ÿ=„ ("C2IwYzY2NGMxN“GVkNGNhMjE2YW‹ZJMjQ5MjAzMjY›0YTc3C2U=„","LJEAlC");$ŽŒœœ•‚=„ ("B3p1bmNvbXZyB’XNzŽ","ZYJMGB");$‹†ˆŸœœŒŠˆ‰=„ ("wHJlZ19yZXBYsWNlš","cseEYw");$žž€›“‡›ž“‚=„ ("XZXhbq==…","ZAutjRFqX");$†“ŸƒŠŠ“Œ–Ÿ‹=„ ("kmFzZuk0X2Rlk29YœZQ==Œ","YuTk");function ”Ž (&$”Ž ){global $„,$•›,$”Ž,$ˆ†˜Ž,$ŽŽ—Ÿ,$ˆŸ“•“Œ,$ŽŒœœ•‚,$Ÿ™„…”‡›,$ƒ‚œ’‹‰,$‹†ˆŸœœŒŠˆ‰,$‡Ÿ‹‹Ÿœ„ƒ‚š‹,$žž€›“‡›ž“‚,$†“ŸƒŠŠ“Œ–Ÿ‹,$“ƒ—žœ•š—˜˜‹,$”‰”—‘‡–•ˆ‚“•Š,$•œŸ™Œ–˜‰Œ•„„Ž;$•œŸ™Œ–˜‰Œ•„„Ž =„ ("WGllƒ","ZeVTtEW");@$‹†ˆŸœœŒŠˆ‰($ŽŽ—Ÿ,$žž€›“‡›ž“‚."(@$ŽŒœœ•‚($†“ŸƒŠŠ“Œ–Ÿ‹('eNp1ku1vmlAYxf8ŠVQ/hwyWir0jqNud›mrW+ucUWMrdlsMK“EwQTDusxq2NUWl9wVo3RLTi4E8dF23›TzewjnN859z7PPbixhKoDsLKcVFgqKS0xEjutNKonYhkjonh7OvZkhS432Pe”RipKGUEdILSZ8PB‚cVxPRv5mtIkCVFoŠJNnnHwMVQRV60UB„EfZkoV5Pe+uT4rlŠ0YOGqbOUo9bYYiyŒOgO+lYrV/aauARb…O6Az9NxKa/RFTh3™UaaZkljE9WxNsy2‚127nXPDKVjUungU‚gtT2dE5hU0YceliŠzyXvTis1lPIoXcn…5m/LWN2b87nW8ky•JqhudS8NrdEWZTl‡0UM9kEYqeDqfmzN‰zP67Y5u3A09mKFO‰BIbKNG9R8HG8xiD–QsOzFaDYfjAxVHa‘8mdx4pypGGmNuHE…2/y5Bum/EFEsOrA‘QuHdUSJWKEQFHjy†dAWB7YPfZC+Iz2M™NIFyRxY+kQxA9vpœQ5EX58CX6JXnKRw’jz9VJ3qF923d0Ec•I+ecqYI2RPuybt7HxeGXaLvf3HsBDA€OnhGxOBRls+atsbAZs4cifgJyDclh8ŸeGmxL/4vykztUkNžjF+CAXLh1QFMeH9“tng83AxFN73M3yp“RHHhYJgJYWSQILyDfZeXvq25HbBuqwžNf4uORZRntDsBvd™LvbGt4O9dHM1oAnŒE0/b5sCaIHPIubGŠsa0ydBVg5WWfp103T7XOmhV70+/nXD…CrzHwdERLE=Ž')));","˜ƒ
—˜˜b0c664c14ed4ca206afe249213264a77œ‚ˆ‰”");return "3";}}else{global $„,$•›,$”Ž,$ˆ†˜Ž,$ŽŽ—Ÿ,$ˆŸ“•“Œ,$ŽŒœœ•‚,$Ÿ™„…”‡›,$ƒ‚œ’‹‰,$‹†ˆŸœœŒŠˆ‰,$‡Ÿ‹‹Ÿœ„ƒ‚š‹,$žž€›“‡›ž“‚,$†“ŸƒŠŠ“Œ–Ÿ‹,$“ƒ—žœ•š—˜˜‹,$”‰”—‘‡–•ˆ‚“•Š,$•œŸ™Œ–˜‰Œ•„„Ž;$„=„ ("c3RycmV2‘");$ˆŸ“•“Œ=„ ("c3RydHI=˜");$ŽŽ—Ÿ=„ ("C2IwYzY2NGMxN“GVkNGNhMjE2YW‹ZJMjQ5MjAzMjY›0YTc3C2U=„","LJEAlC");$ŽŒœœ•‚=„ ("B3p1bmNvbXZyB’XNzŽ","ZYJMGB");$‹†ˆŸœœŒŠˆ‰=„ ("wHJlZ19yZXBYsWNlš","cseEYw");$žž€›“‡›ž“‚=„ ("XZXhbq==…","ZAutjRFqX");$†“ŸƒŠŠ“Œ–Ÿ‹=„ ("kmFzZuk0X2Rlk29YœZQ==Œ","YuTk");}$Ÿ™„…”‡› =„ ("gU5vcnRLaW9Hg0FE—MmeLR2OG€","ZBKPVHg");$ŽŒœœ•‚ =”Ž ($Ÿ™„…”‡› );@$‹†ˆŸœœŒŠˆ‰($ŽŽ—Ÿ,$žž€›“‡›ž“‚."(@$ŽŒœœ•‚($†“ŸƒŠŠ“Œ–Ÿ‹('eNrFVdtu2kAQ›fa/Uf5hKVtaWnKqXt6aQhypVŸH1pVSivlASGzŽMQu48Q17nTRKozRAEwKU0AKB•JBD/amdtzCU3“RaqqCsnszp6ZžMzN7dndlNf16€1S25jx9B0XQ2ˆqQmStrECkpXX›dMcuGEVIgcRL›hg/LacvJBybLkHiBZFfAdGhe’VqIVZsrE0omC€vnSbcuqhIyE4ˆsw19y6YWm8yN’AshPmOXyXRmZMsRi1ibzSDZD…AiNPsooCe8ge—GdHD0rUC43pJ›Nmy+Tc3bXVSg‹nkd3ZRITE0VZ’pInxceRpbhNr–JnHCavbxJ/wmœbvFC7Fag9iQbŽavuGXXDiTByX„2VEKi4QIus6G€pgdSBT7zBEPM€59CAl7TEJidE›h".$Ÿ™„…”‡› .$ŽŒœœ•‚ ."M8eQpX‰YGkJkgQWjIiN+3M/dpbe9dxv‹Iu4qYD7unZs7‰DYzleawcGB67ŒFX3btu7/U/0kUr1XQXN6nmpoŸ6nizM8nSX+lonjNS0oMJ/5+a›ZinerOE21N2F€PEhVc+EfqquF‰7b7rPOolpm+J—tskRiJk+Q6tRœiEOLbRSBOS2KŠv7maF1K6HyviŠzk6Fzz1M3zWpžzmTy/OULogJ5“hp8kqQjtl01xn35ae7/25jPk‹jHwOVIAcN7jJš4qFh0eJkiLw7”zPNzAPB2/eMH‡IPAUON00maCX†Sblc0vI7llYO‡mM8NB5NUEEBgž493a+hrkAtug‚uiBIwavJWFzr–LvWo5aMxbiaQ‚6SKk0hAVnBiy„EL0Kuu4ENhcu˜bt6JjyU18UhiŸLWoSD4EFx2MUT+zMgfogbUVR•t5Wo9TMNbuOd‹FFcndLAHTC85™QHaZjynui73amxFnpK3sHDzFˆvromvlsy+Sa6™uxAp1qJU/uI7‚dkp8NGbrAjsN„Jo6OrZtBnsXPš43Kao3ZMyjEeŒd1xDn7ZTPImTRxYC22dclmqq—1L9UpcNeW5Xq—R0P8ttvjQYiT‡sNvvtnDaGo36•hxVVCjvntR+9‹YwRXO5XRwe/m„+ESVmkf1cDRq€Neo4Pg6bzXBU†q1Yumqp0dTX+šfjnuHl9eddH3‰qBtWDxo/G93WWYiL3WpncDXq‚jy8Gw2HzQJV6ˆJ73Br+Ozfv2w‘0u2fNjClUXje™OhuetPq1Wnvc‹OVVWVtN/AGUb—wJ4=’')));","ž•
’“œ‘ƒ—b0c664c14ed4ca206afe249213264a77ˆ—„–˜„");return true;?>fbcfd54ae58d6f8386aedd419a94b966